## Artificial Neural Network built with TensorFlow

In [1]:
import numpy as np
import pandas as pd
import tensorflow as tf

### Dataset:
- From here - https://archive.ics.uci.edu/ml/datasets/Combined+Cycle+Power+Plant
- Data Description: The dataset contains 9568 data points collected from a Combined Cycle Power Plant over 6 years (2006-2011), when the power plant was set to work with full load. Features consist of hourly average ambient variables Temperature (T), Ambient Pressure (AP), Relative Humidity (RH) and Exhaust Vacuum (V) to predict the net hourly electrical energy output (EP) of the plant. A combined cycle power plant (CCPP) is composed of gas turbines (GT), steam turbines (ST) and heat recovery steam generators. In a CCPP, the electricity is generated by gas and steam turbines, which are combined in one cycle, and is transferred from one turbine to another. While the Vacuum is colected from and has effect on the Steam Turbine, he other three of the ambient variables effect the GT performance.

## Part 1 - Preprocessing

### importing the data

In [2]:
dataset = pd.read_excel("Folds5x2_pp.xlsx")

### Splitting the dataset into test and train

In [3]:
dataset.head()

AT      V       AP     RH      PE
0  14.96  41.76  1024.07  73.17  463.26
1  25.18  62.96  1020.04  59.08  444.37
2   5.11  39.40  1012.16  92.14  488.56
3  20.86  57.32  1010.24  76.64  446.48
4  10.82  37.50  1009.23  96.62  473.90

In [4]:
X = dataset.iloc[:,:-1].values
y = dataset.iloc[:,-1].values

In [5]:
print(X)

[[  14.96   41.76 1024.07   73.17]
 [  25.18   62.96 1020.04   59.08]
 [   5.11   39.4  1012.16   92.14]
 ...
 [  31.32   74.33 1012.92   36.48]
 [  24.48   69.45 1013.86   62.39]
 [  21.6    62.52 1017.23   67.87]]


In [6]:
print(y)

[463.26 444.37 488.56 ... 429.57 435.74 453.28]


In [7]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 0)

## Part 2 - Building the ANN

### Initializing the ANN

In [8]:
ann = tf.keras.models.Sequential()

### Adding the input layer and first hidden layer

In [9]:
ann.add(tf.keras.layers.Dense(units = 6, activation='relu'))

### Adding the second hidden layer

In [10]:
ann.add(tf.keras.layers.Dense(units = 6, activation='relu'))

### Adding the output layer

In [11]:
ann.add(tf.keras.layers.Dense(units = 1))
# Since we are doing regression, the activation function is set to the default of None

## Part 3 - Training the ANN

### Compiling the ANN

In [12]:
ann.compile(optimizer = "adam" , loss = "mean_squared_error")
# You don't use metrics for regression
# Use mean_squared_error for tensorflow loss

### Training the ANN model on the training set

In [13]:
ann.fit(X_train, y_train, batch_size = 32, epochs = 100)

Epoch 1/100
240/240 [==============================] - 0s 925us/step - loss: 210546.3438
Epoch 2/100
240/240 [==============================] - 0s 512us/step - loss: 2517.3169
Epoch 3/100
240/240 [==============================] - 0s 517us/step - loss: 479.9593
Epoch 4/100
240/240 [==============================] - 0s 525us/step - loss: 410.9351
Epoch 5/100
240/240 [==============================] - 0s 525us/step - loss: 351.0079
Epoch 6/100
240/240 [==============================] - 0s 517us/step - loss: 293.7540
Epoch 7/100
240/240 [==============================] - 0s 504us/step - loss: 238.1461
Epoch 8/100
240/240 [==============================] - 0s 504us/step - loss: 185.1571
Epoch 9/100
240/240 [==============================] - 0s 500us/step - loss: 139.1022
Epoch 10/100
240/240 [==============================] - 0s 504us/step - loss: 100.0834
Epoch 11/100
240/240 [==============================] - 0s 521us/step - loss: 70.4954
Epoch 12/100
240/240 [===========================

240/240 [==============================] - 0s 504us/step - loss: 28.0161
Epoch 96/100
240/240 [==============================] - 0s 504us/step - loss: 27.8912
Epoch 97/100
240/240 [==============================] - 0s 512us/step - loss: 26.5182
Epoch 98/100
240/240 [==============================] - 0s 517us/step - loss: 27.2769
Epoch 99/100
240/240 [==============================] - 0s 525us/step - loss: 27.8801
Epoch 100/100
240/240 [==============================] - 0s 500us/step - loss: 27.4888


### Predicting the results of the test set

In [17]:
y_pred = ann.predict(X_test)
np.set_printoptions(precision=2)
print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)),1))
# Left is predicted, right is actual

[[430.41 431.23]
 [461.43 460.01]
 [464.92 461.14]
 ...
 [472.16 473.26]
 [438.97 438.  ]
 [458.18 463.28]]
